import 'dart:io';

final contentTypeMapping = <String, ContentType>{
  '.js': ContentType('text', 'javascript'),
  '.mjs': ContentType('text', 'javascript'),
  '.json': ContentType('text', 'json'),
  '.wasm': ContentType('application', 'wasm'),
  '.css': ContentType('text', 'css'),
  '.png': ContentType('image', 'png'),
  '.jpg': ContentType('image', 'jpeg'),
  '.jpeg': ContentType('image', 'jpeg'),
  '.webp': ContentType('image', 'webp'),
  '.avif': ContentType('image', 'avif'),
  '.svg': ContentType('image', 'svg+xml'),
  '.ttf': ContentType('application', 'x-font-ttf'),
  '.woff': ContentType('application', 'x-font-woff'),
  '.pdf': ContentType('application', 'pdf'),
  '.mp3': ContentType('audio', 'mpeg'),
  '.opus': ContentType('audio', 'opus'),
  '.aac': ContentType('audio', 'aac'),
  '.mp4': ContentType('video', 'mp4'),
  '.webm': ContentType('video', 'webm'),
  '.mkv': ContentType('video', 'x-matroska'),
  '.txt': ContentType('text', 'plain'),
  '.html': ContentType('text', 'html'),
  '.htm': ContentType('text', 'html'),
  '.xml': ContentType('text', 'xml'),
  '.zip': ContentType('application', 'zip'),
  '.gz': ContentType('application', 'gzip'),
  '.tar': ContentType('application', 'x-tar'),
};
