# This is the configuration file for your local development environment. By
# default, it runs a single server on port 8080. To set up your server, you will
# need to add the name of the database you are connecting to and the user name.
# The password for the database is stored in the config/passwords.yaml.
#
# When running your server locally, the server ports are the same as the public
# facing ports.

# Configuration for the main API server.
apiServer:
  port: 8095
  publicHost: localhost
  publicPort: 8095
  publicScheme: http

# Configuration for the Insights server.
insightsServer:
  port: 8096
  publicHost: localhost
  publicPort: 8096
  publicScheme: http

# Configuration for the web server.
webServer:
  port: 8097
  publicHost: localhost
  publicPort: 8097
  publicScheme: http

# This is the database setup for your server.
database:
  host: localhost
  port: 8090
  name: fluttcloud
  user: postgres
  #requireSsl: true # defaults to false
  #isUnixSocket: true # defaults to false

# This is the setup for Redis.
redis:
  enabled: false
  host: localhost
  port: 8091
  #user: # defaults to empty
  #requireSsl: true # defaults to false

maxRequestSize: 524288 # The maximum size of requests allowed in bytes

sessionLogs:
  persistentEnabled: true
  consoleEnabled: true
  consoleLogFormat: text # Defaults to "json", options are "text" or "json"

# futureCallExecutionEnabled: true # Defaults to true

#futureCall:
#  concurrencyLimit: 1 # Defaults to 1, a negative or null value removes the limit
#  scanInterval: 5000 # Unit in milliseconds, defaults to 5000
