name: Docker

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      DEPLOY_PROD:
        type: boolean
        default: false
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-docker
  cancel-in-progress: true

jobs:
  build_client:
    uses: ./.github/workflows/build_client.yml
    with:
      ONLY_WEB: true
    secrets: inherit

  build_server:
    needs: build_client
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Download web build artifact
        uses: actions/download-artifact@v4
        with:
          name: web-app
          path: fluttcloud_server/web/app

      - name: List web build directory
        run: |
          echo "Current directory:"
          ls -l
          echo "Web app directory:"
          ls -lR fluttcloud_server/web/app

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/fluttcloud
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest,enable=${{inputs.DEPLOY_PROD == true}}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        env:
          BUILD_NUMBER: ${{ github.run_number }}
        with:
          context: .
          push: true
          file: ./docker/Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_NUMBER=${{ github.run_number }}
